[source.row-parquet]
type = "parquet"
path = "examples/parquet/row.parquet"
metadata_type = "csv"
metadata = "examples/csv/row-metadata.csv"

[source.dir-parquet]
type = "parquet"
format = "dir"
path = "examples/parquet/dir"
metadata_type = "csv"
metadata = "examples/csv/dir-metadata.csv"

[source.pivot-parquet]
type = "parquet"
format = "pivot"
path = "examples/parquet/pivot.parquet"
metadata_type = "csv"
metadata = "examples/csv/pivot-metadata.csv"
