[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py38"
select = [
    "ARG",
    "B",
    "C4",
    "D",
    "DTZ",
    "E",
    "F",
    "I",
    "N",
    "PD",
    "PL",
    "PLW",
    "Q",
    "RET",
    "T20",
]
ignore = [
    "C408",
    "D105",
    "D107",
    "D203",
    "D213",
    "RET504",
]
line-length = 120

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"kukur/__init__.py" = [
    "I001",
]
"tests/**.py" = [
    "ARG001",
    "ARG002",
    "D",
    "PLR",
]

[tool.pytest.ini_options]
markers = [
    "crate",
    "influxdb",
    "kukur",
    "odbc",
    "postgresql",
]
