[source.row]
type = "csv"
path = "examples/csv/row.csv"
metadata = "examples/csv/row-metadata.csv"
dictionary_dir = "examples/csv/dictionary"

[source.mapping]
type = "csv"
path = "examples/csv/mapping.csv"
metadata = "examples/csv/mapping-metadata.csv"
metadata_mapping = "examples/csv/mapping-mapping.csv"

[source.pivot]
type = "csv"
path = "examples/csv/pivot.csv"
metadata = "examples/csv/pivot-metadata.csv"
format = "pivot"

[source.dir]
type = "csv"
path = "examples/csv/dir"
metadata = "examples/csv/dir-metadata.csv"
format = "dir"
