// SPDX-FileCopyrightText: 2022 Timeseer.AI
// SPDX-License-Identifier: Apache-2.0

== Azure Data Explorer

Sources with `type = "azure-data-explorer"` configure https://azure.microsoft.com/products/data-explorer/[Azure Data Explorer] sources.

The https://github.com/Azure/azure-kusto-python[azure-kusto-data] Python package is required.

```toml
[source.<name>]
type = "azure-data-explorer"
connection_string = "<connection_string>"
client_id = "" # optional: Client ID for authentication
client_secret = "" # optional: Client Secret for authentication
tenant_id = "" # optional: Entra Id Tenant for authentication.
database = "<database>"
table = "<table>" # optional when `list_query` and `data_query` are defined
timestamp_column = "ts"
tag_columns = []
field_columns = []
metadata_columns = []
metadata_mapping = ""
metadata_value_mapping = ""
list_query = "" # optional when `table` is defined
data_query = "" # optional when `table` is defined
data_query_named_parameters = {}
max_items_per_call = 500000
throttle_backoff_count = 8 # The number of times to retry requests using exponential backoff when throttled
```

`connection_string` and `database` are required.

See https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto[here] to learn more about connection strings.

By default,
the https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity#defaultazurecredential[DefaultAzureCredential]
from the https://pypi.org/project/azure-identity/[azure-identity] package is used for authentication.

To use a Service Principal, configure all three of `client_id`, `client_secret` and `tenant_id`.

`max_items_per_call` configures the maximum number of rows to return in one response.
This can be adapted to conform to the https://learn.microsoft.com/en-us/kusto/concepts/query-limits[Kusto Query Limits].

When all data in a table needs to be queried,
define `table`.
When extra filter operations need to be applied,
define `list_query` and `data_query.`

`timestamp_column` is an optional parameter used to define the name
of the database column that contains timestamps for the series.
Defaults to `"ts"`.

Listing time series in an Azure Data Explorer table is supported only when the `tag_columns` parameter is specified.
Each value in the parameter is a column in the table that will be part of the set of tags of the series.
Fields are specified by `field_columns`.

For example:

```toml
tag_columns = [
    "deviceId",
    "plant",
    "location",
]
field_columns = [
    "pressure",
    "temperature",
]
```

Metadata columns can be defined as a list in the `metadata_columns` parameter.

For example:

```toml
metadata_columns = [
    "unit",
]
```

Columns in a metadata often do not match the names of metadata fields in Kukur.
An optional `metadata_mapping` maps Kukur field names to column names.

Example:

```toml
[source.<name>]
metadata_mapping = "example_metadata_mapping"

[metadata_mapping.example_metadata_mapping]
description = "DESCRIPTION"
unit = "ENG_UNITS"
```

Fields that are not included in the mapping,
such as `functional lower limit` in the example,
translate to the corresponding metadata field or are skipped altogether.

Metadata mappings can be shared between sources.

Values in a metadata column can also be different.
The optional `metadata_value_mapping` maps Kukur metadata field values to values as they appear in a source.

Example:

```toml
[source.<name>]
metadata_value_mapping = "example_value_mapping"

[metadata_value_mapping.example_value_mapping."interpolation type"]
LINEAR = "linear"
STEPPED = "stepped"

[metadata_value_mapping.example_value_mapping."data type"]
FLOAT64 = ["int16", "int32"]
```

In this example,
when the `interpolation type` column contains the value `linear`,
Kukur will interpret it as the expected uppercase `LINEAR`.
When the `data type` column contains either `int16` or `int32`,
Kukur will interpret it as `FLOAT64`.

`metadata_mapping` and `metadata_value_mapping` can be used together
to map wildly different metadata formats to a format supported by Kukur.

=== Custom Queries

When time series metadata and data are in separate tables or additional filtering needs to be applied,
custom queries can be defined using `list_query` and `data_query`.

`list_query` should return all columns defined in `tag_columns` and `metadata_columns`.

`data_query` should return the `timestamp_column` and all `field_columns`.
Named parameters for the start and end date of the time range to be queried are passed as `startDate` and `endDate`.
The `data_query` should define these https://learn.microsoft.com/en-us/kusto/query/query-parameters-statement[parameters].
`data_query_named_parameters` maps further parameter names to series tags.

The following example shows how to connect to a source that defined separate tables for metadata and data.
The link between both is made by an internal id that is mapped to the `__id__` tag in Kukur:

```toml
[source.timeseries]
type = "azure-data-explorer"
connection_string = "https://tsaitelemetry.westeurope.kusto.windows.net"
database = "telemetry"
timestamp_column = "timestamp"
tag_columns = ["series name", "__id__"]
field_columns = ["value"]
metadata_columns = ["description"]
list_query = """
['timeseries-metadata']
| project-rename ['__id__'] = ['id']
| project-rename ['series name'] = ['tag']
"""
data_query = """
declare query_parameters (startDate: string, endDate: string, tagid: string);
['timeseries-data']
| where ['timestamp'] >= todatetime(startDate)
| where ['timestamp'] < todatetime(endDate)
| where ['id'] == tagid
| project ['timestamp'], ['value']
| sort by ['timestamp'] asc
"""
data_query_named_parameters = {"tagid" = "__id__"}
```
