// SPDX-FileCopyrightText: 2022 Timeseer.AI
// SPDX-License-Identifier: Apache-2.0

== Azure Data Explorer

Sources with `type = "data_explorer"` configure https://azure.microsoft.com/products/data-explorer/[Delta Lake] sources.

Delta Lake supports the `row` and `pivot` formats:

```toml
[source.<name>]
type = "data_explorer"
connection_string = "<connection_string>"
database = "<database>"
table = "<table>"
```

`database`, `table` and `connection_string` are required.

See https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/connection-strings/kusto[here] to learn more about connection strings.

Metadata in Data explorer is not supported.
Use a different `metadata_type` to connect to metadata.

For example:

```toml
metadata_type = "csv"
```

=== Connecting to Azure Data Explorer

The https://github.com/Azure/azure-kusto-python[azure-kusto-data] library used by Kukur has limited support for https://github.com/Azure/azure-kusto-python#authentication-methods[azure authentication methods].
The method used by kukur is `AAD application` and the authentication parameters must be provided through environment variables, this means one instance of Kukur is able to connect to only one azure active directory application at a time.

The required environment variables are:

* AAD_APP_ID: Active directory application (client) ID
* AAD_APP_KEY: Active directory application (client) secret
* AAD_AUTHORITY_ID: Active directory (tenant) ID

For example:

```toml
[source."Data explorer example"]
type = "data_explorer"
connection_string = "https://help.kusto.windows.net/Samples; Fed=true; Accept=true"
database = "tsai-antewerp"
table = "sensor-data"
```
