// SPDX-FileCopyrightText: 2024 Timeseer.AI
// SPDX-License-Identifier: Apache-2.0

== Elasticsearch

Sources with `type = "elasticsearch"` configure https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html[Elasticsearch] sources.


```toml
[source.<name>]
type = "elasticsearch"
scheme = "http://"
host = "localhost"
port = 9200
index = ""
list_index = ""
tag_columns = []
field_columns = []
metadata_columns = []
metadata_field_column = ""
timestamp_column = ""
search_query = ""
metadata_query = ""
metadata_mapping = ""
metadata_value_mapping = ""
query_timeout_seconds = 60
```

`index` is required.
It refers to the Elasticsearch index.

`list_index` is optional and defaults to `index` if not provided.
It can be used to refer to a different Elasticsearch index for listing time series and their metadata.

Currently https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html[Query DSL] is supported.

`timestamp_column` is an optional parameter used to define the name
of the database column that contains timestamps for the series.
Defaults to `"ts"`.

Listing time series in Elasticsearch is supported only when the `tag_columns` and `field_columns` or `metadata_field_column` parameters are specified.

For example:

```toml
tag_columns = [
    "deviceId",
    "plant",
    "location",
]
```

Metadata columns can be defined as a list in the `metadata_columns` parameter.

For example:

```toml
metadata_columns = [
    "unit",
]
```

Field columns can be defined as a list in the `field_columns` parameter.

For example:

```toml
field_columns = [
    "temperature",
]
```

Columns in a metadata often do not match the names of metadata fields in Kukur.
An optional `metadata_mapping` maps Kukur field names to column names.

Example:

```toml
[source.<name>]
metadata_mapping = "example_metadata_mapping"

[metadata_mapping.example_metadata_mapping]
description = "DESCRIPTION"
unit = "ENG_UNITS"
```

Fields that are not included in the mapping,
such as `functional lower limit` in the example,
translate to the corresponding metadata field or are skipped altogether.

Metadata mappings can be shared between sources.

Values in a metadata column can also be different.
The optional `metadata_value_mapping` maps Kukur metadata field values to values as they appear in a source.

Example:

```toml
[source.<name>]
metadata_value_mapping = "example_value_mapping"

[metadata_value_mapping.example_value_mapping."interpolation type"]
LINEAR = "linear"
STEPPED = "stepped"

[metadata_value_mapping.example_value_mapping."data type"]
FLOAT64 = ["int16", "int32"]
```

In this example,
when the `interpolation type` column contains the value `linear`,
Kukur will interpret it as the expected uppercase `LINEAR`.
When the `data type` column contains either `int16` or `int32`,
Kukur will interpret it as `FLOAT64`.

`metadata_mapping` and `metadata_value_mapping` can be used together
to map wildly different metadata formats to a format supported by Kukur.

Credentials can be added in a separate credential config.

For example:
```
[source.<name>.credentials]
username = ""
password = ""
api_key = ""
```

either username and password needs to be provided or the encoded value of the api key provided by Elasticsearch.


`search_query` refers to a SQL query that can be used to search time series.
When `search_query` is provided the https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest.html[Elasticsearch SQL] query is used for search requests.

`metadata_query` refers to a SQL query that can be used to get metadata of a time series.
When `metadata_query` is provided the https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest.html[Elasticsearch SQL] query is used for metadata requests.

`query_timeout_seconds` configures the timeout of the API request to Elasticsearch.