// SPDX-FileCopyrightText: 2021 Timeseer.AI
//
// SPDX-License-Identifier: Apache-2.0
== Apache Feather

Sources with `type = "feather"` configure https://arrow.apache.org/docs/python/feather.html[Apache Feather] sources.

Feather supports the same source layouts as CSV:

```
[source.<name>]
type = "feather"
format = "row|dir|pivot"
path = "<path to data>"
quality_mapping = "<name>"
```

`path` is required.

`format` defaults to `"row"`.

Metadata in Feather is not supported.
Use a different `metadata_type` to connect to metadata.

For example:

```toml
metadata_type = "csv"
```

=== Row format

```toml
format = "row"
```

The row based format expects `path` to be a Feather file with at least 3 columns:

- The first column contains the `series name` as a string
- The second column contains the timestamp as https://arrow.apache.org/docs/python/generated/pyarrow.TimestampType.html#pyarrow.TimestampType[`pyarrow.TimestampType`].
- The third column contains the value as a numerical type or as strings

=== Directory Based Format

```toml
format = "dir"
```

The directory based format expects `path` to be a directory containing Feather files.
Each file inside `path` is named `<series name>.feather`.

The Feather file contains at least 2 columns:

- The first column contains the timestamp as https://arrow.apache.org/docs/python/generated/pyarrow.TimestampType.html#pyarrow.TimestampType[`pyarrow.TimestampType`].
- The second column contains the value as a numerical type or a string

=== Pivot Format

```toml
format = "pivot"
```

The pivot format expect `path` to be a Feather file.

The first column in the file is a timestamp.
Further columns contain the values.
Some columns can be numerical while other columns contain strings.
The name of each column is the series name.

=== Quality

There is a possibility to add a quality column in the Feather file.
Check the
ifdef::sources[]
<<Quality, source documentation>>
endif::sources[]
ifndef::sources[]
link:sources.asciidoc#Quality[source documentation]
endif::sources[]
to configure the mapping of a value in the quality column to a quality status known to Kukur.

A quality column is not available for a Feather file with a pivot data format.
