// SPDX-FileCopyrightText: 2025 Timeseer.AI
// SPDX-License-Identifier: Apache-2.0

== PI Asset Framework Element Template using Web API

Sources with `type = "piwebapi-af-template"` configure connections to AVEVA (OSIsoft) PI Asset Framework using the PI Web API.
Inside the Asset Framework,
only elements of a given Element Template will be returned.

```toml
[source.<name>]
type = "piwebapi-af-template"
web_api_uri = "" # Required: the URI of PI Web API
root_uri = "" # The URI of the root element to start the search
element_template = "" # The name of the template
element_category = "" # optional: return only attributes of elements with this category
attribute_names = [] # optional: return only these attributes
attribute_category = "" # optional: return only attributes with this category
max_returned_items_per_call = 150000
verify_ssl = true
timeout_seconds = 60 # The maximum time to wait for a response
username = "" # optional: username for basic authentication
password = "" # optional: password for basic authentication
```

`web_api_uri` is a required field.
It is the URI of PI Web API, for example: `https://pi.example.org/piwebapi/`

`root_uri` is the URI of an element resource in a PI Web API database.
This can be either the URI of the full list of elements in a database or the URI of the child elements of an element in the structure.

To get this value,
open `https://pi.example.org/piwebapi/assetservers`,
follow the link to the `Databases` on the correct asset server and copy the `Elements` link from the response:

```
{
  "Links": {},
  "Items": [
    {
      "WebId": "F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI",
      "Id": "994e1f8d-9f26-4186-9f17-4f6258871a23",
      "Name": "Timeseer",
      "Description": "Timeseer.AI Test Database",
      "Path": "\\\\vm-ts-pi\\Timeseer",
      "ExtendedProperties": {},
      "Links": {
        "Self": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI",
        "Elements": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/elements",
        "ElementTemplates": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/elementtemplates",
        "EventFrames": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/eventframes",
        "AssetServer": "https://pi.timeseer.ai/piwebapi/assetservers/F1RSMyvy4jYfVEyvgGiLVLmYvAVk0tVFMtUEk",
        "ElementCategories": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/elementcategories",
        "AttributeCategories": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/attributecategories",
        "TableCategories": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/tablecategories",
        "AnalysisCategories": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/analysiscategories",
        "AnalysisTemplates": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/analysistemplates",
        "EnumerationSets": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/enumerationsets",
        "Tables": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/tables",
        "Security": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/security",
        "SecurityEntries": "https://pi.timeseer.ai/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/securityentries"
      }
    }
  ]
}
```

`attribute_names` allows selecting a subset of (child) attributes of an element.

For example:

```toml
attribute_names = [
    "Status|Active",
    "Level",
]
```

The PI Web API configuration limits the https://docs.osisoft.com/bundle/pi-web-api/page/restrictions-on-number-of-items-per-call.html[maximum number of items] returned in a response to one request.
This limit is applied to the number of time series (PI Points) and to the number of values.
The default setting is `150000`.

Adapt the number in the Kukur configuration when it has been increased or decreased on the server.

Increase `timeout_seconds` when responses could take longer than the already long 2 minutes.
Use with `query_retry_count` and `query_retry_delay` to work around flaky connections.

Set `verify_ssl` to `false` when PI Web API uses a self-signed certificate.

By default,
Kerberos https://docs.osisoft.com/bundle/pi-web-api/page/authentication-methods.html[authentication] is tried.
When Basic authentication is required,
set the `username` and `password` fields in the configuration.

For example,
this defines an `af-template` source,
with the Web API running on `pi.example.org`.

All attributes of the `Reactor` template will be made available.

```toml
[source.af-template]
type = "piwebapi-af-template"
web_api_uri = "https://pi.example.org"
root_uri = "https://pi.example.org/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/elements"
template_name = "Reactor"
```

When the Web API is using a self-signed certificate and basic authentication,
the configuration becomes:

```toml
[source.af]
type = "piwebapi-af-template"
web_api_uri = "https://pi.example.org"
verify_ssl = false
username = "auser"
password = "apassword"
root_uri = "https://pi.example.org/piwebapi/assetdatabases/F1RDMyvy4jYfVEyvgGiLVLmYvAjR9OmSafhkGfF09iWIcaIwVk0tVFMtUElcVElNRVNFRVI/elements"
template_name = "Reactor"
```

