// SPDX-FileCopyrightText: 2022 Timeseer.AI
// SPDX-License-Identifier: Apache-2.0

== PI Data Archive using Web API

Sources with `type = "piwebapi-da"` configure connections to OSIsoft PI Data Archive using the PI Web API.

```toml
[source.<name>]
type = "piwebapi-da"
data_archive_uri = "The self-URI of the DataServer"
max_returned_items_per_call = 150000
verify_ssl = true
timeout_seconds = 60 # The maximum time to wait for a response
username = "" # optional: username for basic authentication
password = "" # optional: password for basic authentication
```

`data_archive_uri` is a required field.

`data_archive_uri` is the URI of the `DataServer` resource in PI Web API that corresponds to the Data Archive.

To get this value,
open `https://pi.example.org/piwebapi/dataservers` and copy the `Self` link from the response:

```
{
  "Links": {},
  "Items": [
    {
      "WebId": "F1DSBd9Ab83Y90SNSjy4JtD5fQVk0tVFMtUEk",
      "Id": "6f40df05-d9cd-44f7-8d4a-3cb826d0f97d",
      "Name": "mypiserver",
      "Path": "\\\\PIServers[mypiserver]",
      "IsConnected": true,
      "ServerVersion": "3.4.440.477",
      "ServerTime": "2022-02-18T15:10:08.8757629Z",
      "Links": {
        "Self": "https://pi.example.org/piwebapi/dataservers/F1DSBd9Ab83Y90SNSjy4JtD5fQVk0tVFMtUEk",
        "Points": "https://pi.example.org/piwebapi/dataservers/F1DSBd9Ab83Y90SNSjy4JtD5fQVk0tVFMtUEk/points",
        "EnumerationSets": "https://pi.example.org/piwebapi/dataservers/F1DSBd9Ab83Y90SNSjy4JtD5fQVk0tVFMtUEk/enumerationsets"
      }
    }
  ]
}
```

The PI Web API configuration limits the https://docs.osisoft.com/bundle/pi-web-api/page/restrictions-on-number-of-items-per-call.html[maximum number of items] returned in a response to one request.
This limit is applied to the number of time series (PI Points) and to the number of values.
The default setting is `150000`.

Adapt the number in the Kukur configuration when it has been increased or decreased on the server.

Increase `timeout_seconds` when responses could take longer than the already long 2 minutes.
Use with `query_retry_count` and `query_retry_delay` to work around flaky connections.

Set `verify_ssl` to `false` when PI Web API uses a self-signed certificate.

By default,
Kerberos https://docs.osisoft.com/bundle/pi-web-api/page/authentication-methods.html[authentication] is tried.
When Basic authentication is required,
set the `username` and `password` fields in the configuration.

For example,
this defines a `pi` source,
with the Web API running on `pi.example.org`:

```toml
[source.pi]
type = "piwebapi-da"
data_archive_uri = "https://pi.example.org/piwebapi/dataservers/F1DSBd9Ab83Y90SNSjy4JtD5fQVk0tVFMtUEk"
```

When the Web API is using a self-signed certificate and basic authentication,
the configuration becomes:

```toml
[source.pi]
type = "piwebapi-da"
data_archive_uri = "https://pi.example.org/piwebapi/dataservers/F1DSBd9Ab83Y90SNSjy4JtD5fQVk0tVFMtUEk"
verify_ssl = false
username = "auser"
password = "apassword"
```
