from datetime import datetime
from typing import Literal

from .lib import Array, DataType, Scalar

ArrayOrScalar = Array | Scalar | float | int | datetime

def any(array: Array) -> Scalar:
    ...

def all(array: Array) -> Scalar:
    ...

def max(array: Array) -> Scalar:
    ...

def min(array: Array) -> Scalar:
    ...

def mean(array: Array) -> Scalar:
    ...

def sum(array: Array) -> Scalar:
    ...

def is_nan(values: Array) -> Array:
    ...

def cumulative_sum(values: Array, *, skip_nulls: bool = False) -> Array:
    ...

def pairwise_diff(input: Array) -> Array:
    ...

def fill_null(values: Array, fill_value: ArrayOrScalar) -> Array:
    ...

def and_(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def or_(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def equal(x: Array, y: Array) -> Array:
    ...

def not_equal(x: Array, y: Array) -> Array:
    ...

def greater(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def greater_equal(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def less(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def less_equal(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def invert(values: Array) -> Array:
    ...

def add(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def subtract(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def divide(divident: ArrayOrScalar, divisor: ArrayOrScalar) -> Array:
    ...

def multiply(x: ArrayOrScalar, y: ArrayOrScalar) -> Array:
    ...

def sqrt(x: ArrayOrScalar) -> Array:
    ...

def power(base: ArrayOrScalar, exponent: ArrayOrScalar) -> Array:
    ...

def cos(x: ArrayOrScalar) -> Array:
    ...

def sin(x: ArrayOrScalar) -> Array:
    ...

def hour(array: Array) -> Array:
    ...

def day(array: Array) -> Array:
    ...

def month(array: Array) -> Array:
    ...

def year(array: Array) -> Array:
    ...

def strptime(strings: Array, format: str, unit: str) -> Array:
    ...

def assume_timezone(timestamps: Array, timezone: str) -> Array:
    ...

def replace_substring(strings: Array, pattern: str, replacement: str) -> Array:
    ...

def if_else(cond: ArrayOrScalar, left: ArrayOrScalar, right: ArrayOrScalar) -> Array:
    ...

def is_in(values: ArrayOrScalar, value_set: Array) -> Array:
    ...

def cast(array: Array, target_type: DataType | str) -> Array:
    ...


class CountOptions:

    def __init__(self, mode: Literal["only_valid"] | Literal["only_null"] | Literal["all"] = "only_valid"):
        ...
