= Connecting to OSIsoft PI

Kukur connects to OSIsoft PI using the PI OLEDB Provider.

The basic configuration to connect to a PI server `PIADB` is:

[source,toml]
----
[source.PIAB]
type = "adodb"
connection_string = "Provider = PIOLEDB;Data Source = PIAB"
----

To list time series and collect metadata, use:

[source,toml]
----
[source.PIAB]
type = "adodb"
connection_string = "Provider = PIOLEDB;Data Source = PIAB"
list_query = "select tag, descriptor, engunits, zero, zero + span, compdev, pointtype, step, digitalset from pipoint2"
list_columns = ["series name", "description", "unit", "physical lower limit", "physical upper limit", "accuracy", "data type", "interpolation type", "dictionary name"]
metadata_value_mapping = "PI_mapping"
dictionary_query = "select code, name from pids where digitalset = ?"

[metadata_value_mapping.PI_mapping."data type"]
FLOAT64 = ["R", "I", " "]
STRING = "S"
DICTIONARY = "D"

[metadata_value_mapping.PI_mapping."interpolation type"]
LINEAR = 0
STEPPED = 1
----

The example above uses the OSIsoft recommended interpretation of the `zero` and `span` PI point attributes.
Update the calculation of the `physical lower limit` and `physical upper limit` as needed when diverging from this.

The ISO8601/RFC3339 timestamps provided by Kukur to the OLEDB driver when requesting data are not natively accepted.
They need to be converted to a format accepted by PI using `data_query_datetime_format` .

To avoid overloading the data historian, the time span of one query has been limited to one day of data.
Kukur will split and recombine longer queries.

[source,toml]
----
[source.PIAB]
type = "adodb"
connection_string = "Provider = PIOLEDB;Data Source = PIAB"
list_query = "select tag, descriptor, engunits, zero, zero + span, compdev, pointtype, step, digitalset from pipoint2"
list_columns = ["series name", "description", "unit", "physical lower limit", "physical upper limit", "accuracy", "data type", "interpolation type", "dictionary name"]
metadata_value_mapping = "PI_mapping"
dictionary_query = "select code, name from pids where digitalset = ?"
data_query = "select time, value from picomp2 where tag = ? and time >= ? and time < ?"
data_query_datetime_format = "%Y-%m-%d %H:%M:%S"
data_query_interval_seconds = 86400

[metadata_value_mapping.PI_mapping."data type"]
FLOAT64 = ["R", "I", " "]
STRING = "S"
DICTIONARY = "D"

[metadata_value_mapping.PI_mapping."interpolation type"]
LINEAR = 0
STEPPED = 1
----

The PI OLEDB provider expects timestamps in the local time zone.
Kukur provides UTC timestamps.
Should Kukur not be running on a system where the time zone is UTC,
either configure the time zone using the `data_query_timezone` and `data_timezone` configuration option or add the `Time Zone = UTC` https://livelibrary.osisoft.com/LiveLibrary/content/en/oledb-pro-v3/GUID-245A53D3-9B04-4676-9EF8-CB21399F1500#addHistory=true&filename=GUID-838BE162-7485-42BF-BF8E-C6138AA141D8.xml&docid=GUID-D747F282-2206-48F5-8FE2-724418728A06&inner_id=&tid=&query=&scope=&resource=&toc=false&eventType=lcContent.loadDocGUID-D747F282-2206-48F5-8FE2-724418728A06[property] to the `connection_string`.
