name: Create documentation
on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: make docs

      - name: Tag docker image
        run: docker tag kukur-documentation:latest docker.timeseer.ai/kukur-documentation:latest

      - name: Login to container registry
        uses: azure/docker-login@v1
        with:
          login-server: docker.timeseer.ai
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: Push docker image
        run: docker push docker.timeseer.ai/kukur-documentation:latest
        if: github.ref == 'refs/heads/master'

  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy Nomad job
        uses: appleboy/ssh-action@v0.0.9
        with:
          host: ts-vm01.timeseer.ai
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            nomad stop --purge kukur-documentation
            nomad run /opt/nomad-jobs/kukur-documentation.hcl
