name: Create documentation
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'docs/**'

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: make docs

      - name: Tag docker image
        run: docker tag kukur-documentation:latest docker.timeseer.ai/kukur-documentation:latest

      - name: Login to container registry
        uses: azure/docker-login@v1
        with:
          login-server: docker.timeseer.ai
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/master'

      - name: Push docker image
        run: docker push docker.timeseer.ai/kukur-documentation:latest
        if: github.ref == 'refs/heads/master'

  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Load SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Stop previous Nomad job
        run: ssh root@ts-host02.timeseer.ai 'nomad stop --purge kukur-documentation'
        continue-on-error: true

      - name: Run Nomad job
        run: ssh root@ts-host02.timeseer.ai 'nomad run /opt/nomad-jobs/kukur-documentation.hcl'
