name: Publish Kukur
on:
  push:
    tags:
    - v*

jobs:
  pypi:
    name: Publish version to PyPI
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/kukur
    permissions:
      id-token: write
    steps:

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.6"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: uv build

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  docker_hub:
    name: Publish docker container for this version to Docker Hub
    runs-on: ubuntu-24.04
    steps:

    - name: Set version in environment
      run: echo "KUKUR_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Login to Timeseer container registry
      uses: docker/login-action@v3
      with:
        registry: docker.timeseer.ai
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull docker image
      run: docker pull docker.timeseer.ai/kukur:${GITHUB_SHA}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Tag docker image
      run: docker tag docker.timeseer.ai/kukur:${GITHUB_SHA} timeseer/kukur:${KUKUR_VERSION}

    - name: Tag docker image as latest version
      run: docker tag docker.timeseer.ai/kukur:${GITHUB_SHA} timeseer/kukur:latest

    - name: Push docker image
      run: docker push timeseer/kukur:${KUKUR_VERSION}

    - name: Push latest docker image
      run: docker push timeseer/kukur:latest
